insert into People (PersonName, BirthDate, Country)
values ('Yuzuru Hanyu', '1994-12-07', 'Japan'),
       ('Brian Orser', '1961-12-18', 'Canada'),
       ('Tracy Wilson', '1961-09-25', 'Canada'),
       ('Nanami Abe', '1972-11-11', 'Japan'),
       ('Daisuke Takahashi', '1986-03-16', 'Japan'),
       ('Patrick Chan', '1990-12-31', 'Canada'),
       ('Denis Ten', '1993-06-13', 'Kazakhstan'),
       ('Tatiana Tarasova', '1947-02-13', 'Soviet Union'),
       ('Nikolai Morozov', '1975-12-17', 'Belarus'),
       ('Evgenia Medvedeva', '1999-11-19', 'Russia'),
       ('Eteri Tutberidze', '1974-02-24', 'Soviet Union'),
       ('Marina Zueva', '1956-04-09', 'Soviet Union');

create or replace function GetPersonIdByName(in PName varchar(128))
    returns table (
        PersonId int
    )
    language plpgsql
    security definer
as
$$
begin
    return query
    select People.PersonId
    from People
    where PersonName = PName;
end
$$;

create or replace procedure AddNewTrainer(in PName varchar(128), in TName varchar(128))
    language plpgsql
    security definer
as
$$
declare
    PId int;
    TId int;
begin
    select into PId GetPersonIdByName(PName);
    select into TId GetPersonIdByName(TName);
    
    if PId is not null and TId is not null then
        insert into PersonalTrainers (PersonId, TrainerId)
        values (PId, TId);
    end if;
end
$$;

call AddNewTrainer('Yuzuru Hanyu', 'Brian Orser');
call AddNewTrainer('Yuzuru Hanyu', 'Tracy Wilson');
call AddNewTrainer('Yuzuru Hanyu', 'Nanami Abe');
call AddNewTrainer('Daisuke Takahashi', 'Nikolai Morozov');
call AddNewTrainer('Daisuke Takahashi', 'Marina Zueva');
call AddNewTrainer('Patrick Chan', 'Marina Zueva');
call AddNewTrainer('Denis Ten', 'Nikolai Morozov');
call AddNewTrainer('Denis Ten', 'Tatiana Tarasova');
call AddNewTrainer('Evgenia Medvedeva', 'Eteri Tutberidze');
call AddNewTrainer('Evgenia Medvedeva', 'Brian Orser');
call AddNewTrainer('Evgenia Medvedeva', 'Tracy Wilson');

insert into People (PersonName, BirthDate, Country)
values ('BESHENOVA Anna', '1999-01-08', 'Russia'),
       ('GOROKHOVA Veronika', '1998-04-13', 'Russia'),
       ('IVANOVA Anastasia', '1998-12-04', 'Russia'),
       ('KALIMULLINA Kamilla', '1992-07-23', 'Russia'),
       ('KAZAKOVA Nataliia', '1999-09-09', 'Russia'),
       ('KODUSHKEVICH Elizaveta', '1995-08-03', 'Russia'),
       ('KORESHKOVA Milana', '1997-02-10', 'Russia'),
       ('KORNEEVA Karina', '1996-07-12', 'Russia'),
       ('KORZHIKOVA Anastasia', '1998-06-17', 'Russia'),
       ('LUBNIKOVA Elizaveta', '1999-02-04', 'Russia'),
       ('LUKINA Anna', '1994-05-28', 'Russia'),
       ('LUZHINA Anastasiia', '1997-10-21', 'Russia'),
       ('Irina Yakovleva', '1954-03-17', 'Soviet Union');

insert into Teams (TeamName, Country)
values ('Team Paradise', 'Russia');

insert into TeamTrainers (TeamId, TrainerId)
values (1, (select GetPersonIdByName('Irina Yakovleva')));

insert into TeamParticipants (TeamId, PersonId)
values (1, (select GetPersonIdByName('BESHENOVA Anna'))),
       (1, (select GetPersonIdByName('GOROKHOVA Veronika'))),
       (1, (select GetPersonIdByName('IVANOVA Anastasia'))),
       (1, (select GetPersonIdByName('KALIMULLINA Kamilla')));
       
insert into Competitions (CompetitionName, DateStarts, DateEnds)
values ('World Championship in Synchronized Skating', '2019-04-11', '2019-04-13'),
       ('2014 Olympic Winter Games', '2014-02-07', '2014-02-23');

insert into CompetitionStandings (CompetitionId, CompetitionType, CompetitorId, ShortScore, FreeScore, TotalScore)
values (2, 'Single', (select GetPersonIdByName('Yuzuru Hanyu')), 101.45, 178.64, 280.09);

insert into PerformanceDetails (PerformanceId, ElementId, ElementAbbreviation, GOE)
values (1, 1, '4T', 2.86),
       (1, 2, 'FCSp4', 1.00),
       (1, 3, 'CSSp3', 0.79),
       (1, 4, '3A', 2.14),
       (1, 5, '3Lz+3T', 1.50),
       (1, 6, 'StSq4', 1.80),
       (1, 7, 'CCoSp4', 0.79);

insert into PerformanceComponents (PerformanceId, ComponentType, Value, Factor)
values (1, 'Skating skills', 9.36, 1.00),
       (1, 'Transitions', 9.00, 1.00),
       (1, 'Performance', 9.50, 1.00),
       (1, 'Composition', 9.39, 1.00),
       (1, 'Interpretation', 9.36, 1.00);
       
insert into PerformanceDeductions (PerformanceId, Value)
values (1, 0);

insert into ElementInformations (ElementAbbreviation, ElementDescription, SOV)
values ('1A', 'Single Axel', 1.1),
       ('1A<', 'Single Axel under-rotated jump', 0.83),
       ('1ATh', 'Throw Single Axel', 2.2),
       ('1ATh<', 'Throw Single Axel under-rotated jump', 1.65),
       ('1Eu', 'Single Euler (only used in jump combinations)', 0.5),
       ('1Eu<', 'Single Euler (only used in jump combinations) under-rotated jump', 0.38),
       ('1F', 'Single Flip', 0.5),
       ('1F<', 'Single Flip under-rotated jump', 0.38),
       ('1F<e', 'Single Flip under-rotated jump serious error in take off', 0.3),
       ('1Fe', 'Single Flip serious error in take off', 0.38),
       ('1Li1', 'Group 1 Lift (Armpit Hold Position) with 1 spin', 1.5),
       ('1Li2', 'Group 1 Lift (Armpit Hold Position) with 2 spin', 1.7),
       ('1Li3', 'Group 1 Lift (Armpit Hold Position) with 3 spin', 1.9),
       ('1Li4', 'Group 1 Lift (Armpit Hold Position) with 4 spin', 2.1),
       ('1LiB', 'Group 1 Lift (Armpit Hold Position) with B spin', 1.4),
       ('1Lo', 'Single Loop', 0.5),
       ('1Lo<', 'Single Loop under-rotated jump', 0.38),
       ('1LoTh', 'Throw Single Loop', 1.4),
       ('1LoTh<', 'Throw Single Loop under-rotated jump', 1.05),
       ('1Lz', 'Single Lutz', 0.6),
       ('1Lz<', 'Single Lutz under-rotated jump', 0.45),
       ('1Lz<e', 'Single Lutz under-rotated jump serious error in take off', 0.36),
       ('1LzTh', 'Throw Single Lutz', 1.4),
       ('1LzTh<', 'Throw Single Lutz under-rotated jump', 1.05),
       ('1Lze', 'Single Lutz serious error in take off', 0.45),
       ('1S', 'Single Salchow', 0.4),
       ('1S<', 'Single Salchow under-rotated jump', 0.3),
       ('1STh', 'Throw Single Salchow', 1.1),
       ('1STh<', 'Throw Single Salchow under-rotated jump', 0.83),
       ('1T', 'Single Toeloop', 0.4),
       ('1T<', 'Single Toeloop under-rotated jump', 0.3),
       ('1TTh', 'Throw Single Toe Loop', 1.1),
       ('1TTh<', 'Throw Single Toe Loop under-rotated jump', 0.83),
       ('1Tw1', 'Single Twist Lift with 1 spin', 1.1),
       ('1Tw2', 'Single Twist Lift with 2 spin', 1.3),
       ('1Tw3', 'Single Twist Lift with 3 spin', 1.5),
       ('1Tw4', 'Single Twist Lift with 4 spin', 1.7),
       ('1TwB', 'Single Twist Lift with B spin', 0.9),
       ('2A', 'Double Axel', 3.3),
       ('2A<', 'Double Axel under-rotated jump', 2.48),
       ('2ATh', 'Throw Double Axel', 4),
       ('2ATh<', 'Throw Double Axel under-rotated jump', 3),
       ('2F', 'Double Flip', 1.8),
       ('2F<', 'Double Flip under-rotated jump', 1.35),
       ('2F<e', 'Double Flip under-rotated jump serious error in take off', 1.08),
       ('2Fe', 'Double Flip serious error in take off', 1.35),
       ('2Li1', 'Group 2 Lift (Waist Hold Position) with 1 spin', 1.9),
       ('2Li2', 'Group 2 Lift (Waist Hold Position) with 2 spin', 2.3),
       ('2Li3', 'Group 2 Lift (Waist Hold Position) with 3 spin', 2.7),
       ('2Li4', 'Group 2 Lift (Waist Hold Position) with 4 spin', 3.1),
       ('2LiB', 'Group 2 Lift (Waist Hold Position) with B spin', 1),
       ('2Lo', 'Double Loop', 1.7),
       ('2Lo<', 'Double Loop under-rotated jump', 1.28),
       ('2LoTh', 'Throw Double Loop', 2.8),
       ('2LoTh<', 'Throw Double Loop under-rotated jump', 2.1),
       ('2Lz', 'Double Lutz', 2.1),
       ('2Lz<', 'Double Lutz under-rotated jump', 1.58),
       ('2Lz<e', 'Double Lutz under-rotated jump serious error in take off', 1.26),
       ('2LzTh', 'Throw Double Lutz', 3),
       ('2LzTh<', 'Throw Double Lutz under-rotated jump', 2.25),
       ('2Lze', 'Double Lutz serious error in take off', 1.58),
       ('2S', 'Double Salchow', 1.3),
       ('2S<', 'Double Salchow under-rotated jump', 0.98),
       ('2STh', 'Throw Double Salchow', 2.5),
       ('2STh<', 'Throw Double Salchow under-rotated jump', 1.88),
       ('2T', 'Double Toeloop', 1.3),
       ('2T<', 'Double Toeloop under-rotated jump', 0.98),
       ('2TTh', 'Throw Double Toeloop', 2.5),
       ('2TTh<', 'Throw Double Toeloop under-rotated jump', 1.88),
       ('2Tw1', 'Double Twist Lift with 1 spin', 2.8),
       ('2Tw2', 'Double Twist Lift with 2 spin', 3),
       ('2Tw3', 'Double Twist Lift with 3 spin', 3.2),
       ('2Tw4', 'Double Twist Lift with 4 spin', 3.4),
       ('2TwB', 'Double Twist Lift with B spin', 2.6),
       ('3A', 'Triple Axel', 8),
       ('3A<', 'Triple Axel under-rotated jump', 6),
       ('3ATh', 'Throw Triple Axel', 6),
       ('3ATh<', 'Throw Triple Axel under-rotated jump', 4.5),
       ('3F', 'Triple Flip', 5.3),
       ('3F<', 'Triple Flip under-rotated jump', 3.98),
       ('3F<e', 'Triple Flip under-rotated jump serious error in take off', 3.18),
       ('3Fe', 'Triple Flip serious error in take off', 3.98),
       ('3Li1', 'Group 3 Lift (Hand to Hip Position) with 1 spin', 3.9),
       ('3Li2', 'Group 3 Lift (Hand to Hip Position) with 2 spin', 4.3),
       ('3Li3', 'Group 3 Lift (Hand to Hip Position) with 3 spin', 4.7),
       ('3Li4', 'Group 3 Lift (Hand to Hip Position) with 4 spin', 5.1),
       ('3LiB', 'Group 3 Lift (Hand to Hip Position) with B spin', 3.5),
       ('3Lo', 'Triple Loop', 4.9),
       ('3Lo<', 'Triple Loop under-rotated jump', 3.68),
       ('3LoTh', 'Throw Triple Loop', 5),
       ('3LoTh<', 'Throw Triple Loop under-rotated jump', 3.75),
       ('3Lz', 'Triple Lutz', 5.9),
       ('3Lz<', 'Triple Lutz under-rotated jump', 4.43),
       ('3Lz<e', 'Triple Lutz under-rotated jump serious error in take off', 3.54),
       ('3LzTh', 'Throw Triple Lutz', 5.3),
       ('3LzTh<', 'Throw Triple Lutz under-rotated jump', 3.98),
       ('3Lze', 'Triple Lutz serious error in take off', 4.43),
       ('3S', 'Triple Salchow', 4.3),
       ('3S<', 'Triple Salchow under-rotated jump', 3.23),
       ('3STh', 'Throw Triple Salchow', 4.4),
       ('3STh<', 'Throw Triple Salchow under-rotated jump', 3.3),
       ('3T', 'Triple Toeloop', 4.2),
       ('3T<', 'Triple Toeloop under-rotated jump', 3.15),
       ('3TTh', 'Throw Triple Toeloop', 4.4),
       ('3TTh<', 'Throw Triple Toeloop under-rotated jump', 3.3),
       ('3Tw1', 'Triple Twist Lift with 1 spin', 5.1),
       ('3Tw2', 'Triple Twist Lift with 2 spin', 5.4),
       ('3Tw3', 'Triple Twist Lift with 3 spin', 5.7),
       ('3Tw4', 'Triple Twist Lift with 4 spin', 6),
       ('3TwB', 'Triple Twist Lift with B spin', 4.8),
       ('4A', 'Quad. Axel', 12.5),
       ('4A<', 'Quad. Axel under-rotated jump', 9.38),
       ('4F', 'Quad. Flip', 11),
       ('4F<', 'Quad. Flip under-rotated jump', 8.25),
       ('4F<e', 'Quad. Flip under-rotated jump serious error in take off', 6.6),
       ('4Fe', 'Quad. Flip serious error in take off', 8.25),
       ('4Li1', 'Group 4 Lift (Hand to Hand Position) with 1 spin', 3.9),
       ('4Li2', 'Group 4 Lift (Hand to Hand Position) with 2 spin', 4.3),
       ('4Li3', 'Group 4 Lift (Hand to Hand Position) with 3 spin', 4.7),
       ('4Li4', 'Group 4 Lift (Hand to Hand Position) with 4 spin', 5.1),
       ('4LiB', 'Group 4 Lift (Hand to Hand Position) with B spin', 3.5),
       ('4Lo', 'Quad. Loop', 10.5),
       ('4Lo<', 'Quad. Loop under-rotated jump', 7.88),
       ('4LoTh', 'Throw Quad. Loop', 7),
       ('4LoTh<', 'Throw Quad. Loop under-rotated jump', 5.25),
       ('4Lz', 'Quad. Lutz', 11.5),
       ('4Lz<', 'Quad. Lutz under-rotated jump', 8.63),
       ('4Lz<e', 'Quad. Lutz under-rotated jump serious error in take off', 6.9),
       ('4LzTh', 'Throw Quad. Lutz', 7.5),
       ('4LzTh<', 'Throw Quad. Lutz under-rotated jump', 5.63),
       ('4Lze', 'Quad. Lutz serious error in take off', 8.63),
       ('4S', 'Quad. Salchow', 9.7),
       ('4S<', 'Quad. Salchow under-rotated jump', 7.28),
       ('4STh', 'Throw Quad. Salchow', 6.5),
       ('4STh<', 'Throw Quad. Salchow under-rotated jump', 4.88),
       ('4T', 'Quad. Toeloop', 9.5),
       ('4T<', 'Quad. Toeloop under-rotated jump', 7.13),
       ('4TTh', 'Throw Quad. Toe Loop', 6.5),
       ('4TTh<', 'Throw Quad. Toe Loop under-rotated jump', 4.88),
       ('4Tw1', 'Quad. Twist Lift with 1 spin', 6.8),
       ('4Tw2', 'Quad. Twist Lift with 2 spin', 7.2),
       ('4Tw3', 'Quad. Twist Lift with 3 spin', 7.6),
       ('4Tw4', 'Quad. Twist Lift with 4 spin', 8),
       ('4TwB', 'Quad. Twist Lift with B spin', 6.4),
       ('5BLi1', 'Group 5 Backward Lasso Lift with 1 spin', 5.4),
       ('5BLi2', 'Group 5 Backward Lasso Lift with 2 spin', 5.8),
       ('5BLi3', 'Group 5 Backward Lasso Lift with 3 spin', 6.2),
       ('5BLi4', 'Group 5 Backward Lasso Lift with 4 spin', 6.5),
       ('5BLiB', 'Group 5 Backward Lasso Lift with B spin', 5),
       ('5RLi1', 'Group 5 Reverse Lasso Lift with 1 spin', 5.8),
       ('5RLi2', 'Group 5 Reverse Lasso Lift with 2 spin', 6.2),
       ('5RLi3', 'Group 5 Reverse Lasso Lift with 3 spin', 6.6),
       ('5RLi4', 'Group 5 Reverse Lasso Lift with 4 spin', 7),
       ('5RLiB', 'Group 5 Reverse Lasso Lift with B spin', 5.4),
       ('5SLi1', 'Group 5 Step in Lasso Lift with 1 spin', 5),
       ('5SLi2', 'Group 5 Step in Lasso Lift with 2 spin', 5.4),
       ('5SLi3', 'Group 5 Step in Lasso Lift with 3 spin', 5),
       ('5SLi4', 'Group 5 Step in Lasso Lift with 4 spin', 6.2),
       ('5SLiB', 'Group 5 Step in Lasso Lift with B spin', 4.6),
       ('BiDs1', 'Backward Inside Death Spiral with 1 spin', 2.9),
       ('BiDs2', 'Backward Inside Death Spiral with 2 spin', 3.2),
       ('BiDs3', 'Backward Inside Death Spiral with 3 spin', 3.5),
       ('BiDs4', 'Backward Inside Death Spiral with 4 spin', 3.8),
       ('BiDsB', 'Backward Inside Death Spiral with B spin', 2.6),
       ('BoDs1', 'Backward Outside Death Spiral with 1 spin', 3.5),
       ('BoDs2', 'Backward Outside Death Spiral with 2 spin', 3.9),
       ('BoDs3', 'Backward Outside Death Spiral with 3 spin', 4.3),
       ('BoDs4', 'Backward Outside Death Spiral with 4 spin', 4.7),
       ('BoDsB', 'Backward Outside Death Spiral with B spin', 3.1),
       ('CCSp1', 'Change Foot Camel Spin with 1 spin', 2),
       ('CCSp1V', 'Change Foot Camel Spin with 1 spin V', 1.5),
       ('CCSp2', 'Change Foot Camel Spin with 2 spin', 2.3),
       ('CCSp2V', 'Change Foot Camel Spin with 2 spin V', 1.73),
       ('CCSp3', 'Change Foot Camel Spin with 3 spin', 2.8),
       ('CCSp3V', 'Change Foot Camel Spin with 3 spin V', 2.1),
       ('CCSp4', 'Change Foot Camel Spin with 4 spin', 3.2),
       ('CCSp4V', 'Change Foot Camel Spin with 4 spin V', 2.4),
       ('CCSpB', 'Change Foot Camel Spin with B spin', 1.7),
       ('CCSpBV', 'Change Foot Camel Spin with B spin V', 1.28),
       ('CCoSp1', 'Change Foot Combination Spin with 1 spin', 2),
       ('CCoSp1V', 'Change Foot Combination Spin with 1 spin V', 1.5),
       ('CCoSp2', 'Change Foot Combination Spin with 2 spin', 2.5),
       ('CCoSp2V', 'Change Foot Combination Spin with 2 spin V', 1.88),
       ('CCoSp3', 'Change Foot Combination Spin with 3 spin', 3),
       ('CCoSp3V', 'Change Foot Combination Spin with 3 spin V', 2.25),
       ('CCoSp4', 'Change Foot Combination Spin with 4 spin', 3.5),
       ('CCoSp4V', 'Change Foot Combination Spin with 4 spin V', 2.63),
       ('CCoSpB', 'Change Foot Combination Spin with B spin', 1.7),
       ('CCoSpBV', 'Change Foot Combination Spin with B spin V', 1.28),
       ('CLSp1', 'Change Foot Layback Spin with 1 spin', 2),
       ('CLSp1V', 'Change Foot Layback Spin with 1 spin V', 1.5),
       ('CLSp2', 'Change Foot Layback Spin with 2 spin', 2.4),
       ('CLSp2V', 'Change Foot Layback Spin with 2 spin V', 1.8),
       ('CLSp3', 'Change Foot Layback Spin with 3 spin', 2.9),
       ('CLSp3V', 'Change Foot Layback Spin with 3 spin V', 2.18),
       ('CLSp4', 'Change Foot Layback Spin with 4 spin', 3.2),
       ('CLSp4V', 'Change Foot Layback Spin with 4 spin V', 2.4),
       ('CLSpB', 'Change Foot Layback Spin with B spin', 1.7),
       ('CLSpBV', 'Change Foot Layback Spin with B spin V', 1.28),
       ('CSSp1', 'Change Foot Sit Spin with 1 spin', 1.9),
       ('CSSp1V', 'Change Foot Sit Spin with 1 spin V', 1.43),
       ('CSSp2', 'Change Foot Sit Spin with 2 spin', 2.3),
       ('CSSp2V', 'Change Foot Sit Spin with 2 spin V', 1.73),
       ('CSSp3', 'Change Foot Sit Spin with 3 spin', 2.6),
       ('CSSp3V', 'Change Foot Sit Spin with 3 spin V', 1.95),
       ('CSSp4', 'Change Foot Sit Spin with 4 spin', 3),
       ('CSSp4V', 'Change Foot Sit Spin with 4 spin V', 2.25),
       ('CSSpB', 'Change Foot Sit Spin with B spin', 1.6),
       ('CSSpBV', 'Change Foot Sit Spin with B spin V', 1.2),
       ('CSp1', 'Camel Spin with 1 spin', 1.4),
       ('CSp2', 'Camel Spin with 2 spin', 1.8),
       ('CSp3', 'Camel Spin with 3 spin', 2.3),
       ('CSp4', 'Camel Spin with 4 spin', 2.6),
       ('CSpB', 'Camel Spin with B spin', 1.1),
       ('CUSp1', 'Change Foot Upright Spin with 1 spin', 1.7),
       ('CUSp1V', 'Change Foot Upright Spin with 1 spin V', 1.28),
       ('CUSp2', 'Change Foot Upright Spin with 2 spin', 2),
       ('CUSp2V', 'Change Foot Upright Spin with 2 spin V', 1.5),
       ('CUSp3', 'Change Foot Upright Spin with 3 spin', 2.4),
       ('CUSp3V', 'Change Foot Upright Spin with 3 spin V', 1.8),
       ('CUSp4', 'Change Foot Upright Spin with 4 spin', 2.9),
       ('CUSp4V', 'Change Foot Upright Spin with 4 spin V', 2.18),
       ('CUSpB', 'Change Foot Upright Spin with B spin', 1.5),
       ('CUSpBV', 'Change Foot Upright Spin with B spin V', 1.13),
       ('CoSp1', 'Combination Spin with 1 spin', 1.7),
       ('CoSp1V', 'Combination Spin with 1 spin V', 1.28),
       ('CoSp2', 'Combination Spin with 2 spin', 2),
       ('CoSp2V', 'Combination Spin with 2 spin V', 1.5),
       ('CoSp3', 'Combination Spin with 3 spin', 2.5),
       ('CoSp3V', 'Combination Spin with 3 spin V', 1.88),
       ('CoSp4', 'Combination Spin with 4 spin', 3),
       ('CoSp4V', 'Combination Spin with 4 spin V', 2.25),
       ('CoSpB', 'Combination Spin with B spin', 1.5),
       ('CoSpBV', 'Combination Spin with B spin V', 1.13),
       ('FCCSp1', 'Flying Change Foot Camel Spin with 1 spin', 2),
       ('FCCSp1V', 'Flying Change Foot Camel Spin with 1 spin V', 1.5),
       ('FCCSp2', 'Flying Change Foot Camel Spin with 2 spin', 2.3),
       ('FCCSp2V', 'Flying Change Foot Camel Spin with 2 spin V', 1.73),
       ('FCCSp3', 'Flying Change Foot Camel Spin with 3 spin', 2.8),
       ('FCCSp3V', 'Flying Change Foot Camel Spin with 3 spin V', 2.1),
       ('FCCSp4', 'Flying Change Foot Camel Spin with 4 spin', 3.2),
       ('FCCSp4V', 'Flying Change Foot Camel Spin with 4 spin V', 2.4),
       ('FCCSpB', 'Flying Change Foot Camel Spin with B spin', 1.7),
       ('FCCSpBV', 'Flying Change Foot Camel Spin with B spin V', 1.28),
       ('FCCoSp1', 'Flying Change Foot Comb. Spin with 1 spin', 2),
       ('FCCoSp1V', 'Flying Change Foot Comb. Spin with 1 spin V', 1.5),
       ('FCCoSp2', 'Flying Change Foot Comb. Spin with 2 spin', 2.5),
       ('FCCoSp2V', 'Flying Change Foot Comb. Spin with 2 spin V', 1.88),
       ('FCCoSp3', 'Flying Change Foot Comb. Spin with 3 spin', 3),
       ('FCCoSp3V', 'Flying Change Foot Comb. Spin with 3 spin V', 2.25),
       ('FCCoSp4', 'Flying Change Foot Comb. Spin with 4 spin', 3.5),
       ('FCCoSp4V', 'Flying Change Foot Comb. Spin with 4 spin V', 2.63),
       ('FCCoSpB', 'Flying Change Foot Comb. Spin with B spin', 1.7),
       ('FCCoSpBV', 'Flying Change Foot Comb. Spin with B spin V', 1.28),
       ('FCLSp1', 'Flying Change Foot Layback Spin with 1 spin', 2),
       ('FCLSp1V', 'Flying Change Foot Layback Spin with 1 spin V', 1.5),
       ('FCLSp2', 'Flying Change Foot Layback Spin with 2 spin', 2.4),
       ('FCLSp2V', 'Flying Change Foot Layback Spin with 2 spin V', 1.8),
       ('FCLSp3', 'Flying Change Foot Layback Spin with 3 spin', 2.9),
       ('FCLSp3V', 'Flying Change Foot Layback Spin with 3 spin V', 2.18),
       ('FCLSp4', 'Flying Change Foot Layback Spin with 4 spin', 3.2),
       ('FCLSp4V', 'Flying Change Foot Layback Spin with 4 spin V', 2.4),
       ('FCLSpB', 'Flying Change Foot Layback Spin with B spin', 1.7),
       ('FCLSpBV', 'Flying Change Foot Layback Spin with B spin V', 1.28),
       ('FCSSp1', 'Flying Change Foot Sit Spin with 1 spin', 1.9),
       ('FCSSp1V', 'Flying Change Foot Sit Spin with 1 spin V', 1.43),
       ('FCSSp2', 'Flying Change Foot Sit Spin with 2 spin', 2.3),
       ('FCSSp2V', 'Flying Change Foot Sit Spin with 2 spin V', 1.73),
       ('FCSSp3', 'Flying Change Foot Sit Spin with 3 spin', 2.6),
       ('FCSSp3V', 'Flying Change Foot Sit Spin with 3 spin V', 1.95),
       ('FCSSp4', 'Flying Change Foot Sit Spin with 4 spin', 3),
       ('FCSSp4V', 'Flying Change Foot Sit Spin with 4 spin V', 2.25),
       ('FCSSpB', 'Flying Change Foot Sit Spin with B spin', 1.6),
       ('FCSSpBV', 'Flying Change Foot Sit Spin with B spin V', 1.2),
       ('FCSp1', 'Flying Camel Spin with 1 spin', 1.9),
       ('FCSp1V', 'Flying Camel Spin with 1 spin V', 1.43),
       ('FCSp2', 'Flying Camel Spin with 2 spin', 2.3),
       ('FCSp2V', 'Flying Camel Spin with 2 spin V', 1.73),
       ('FCSp3', 'Flying Camel Spin with 3 spin', 2.8),
       ('FCSp3V', 'Flying Camel Spin with 3 spin V', 2.1),
       ('FCSp4', 'Flying Camel Spin with 4 spin', 3.2),
       ('FCSp4V', 'Flying Camel Spin with 4 spin V', 2.4),
       ('FCSpB', 'Flying Camel Spin with B spin', 1.6),
       ('FCSpBV', 'Flying Camel Spin with B spin V', 1.2),
       ('FCUSp1', 'Flying Change Foot Upright Spin with 1 spin', 1.7),
       ('FCUSp1V', 'Flying Change Foot Upright Spin with 1 spin V', 1.28),
       ('FCUSp2', 'Flying Change Foot Upright Spin with 2 spin', 2),
       ('FCUSp2V', 'Flying Change Foot Upright Spin with 2 spin V', 1.5),
       ('FCUSp3', 'Flying Change Foot Upright Spin with 3 spin', 2.4),
       ('FCUSp3V', 'Flying Change Foot Upright Spin with 3 spin V', 1.8),
       ('FCUSp4', 'Flying Change Foot Upright Spin with 4 spin', 2.9),
       ('FCUSp4V', 'Flying Change Foot Upright Spin with 4 spin V', 2.18),
       ('FCUSpB', 'Flying Change Foot Upright Spin with B spin', 1.5),
       ('FCUSpBV', 'Flying Change Foot Upright Spin with B spin V', 1.13),
       ('FCoSp1', 'Flying Combination Spin no change of foot with 1 spin', 1.7),
       ('FCoSp1V', 'Flying Combination Spin no change of foot with 1 spin V', 1.28),
       ('FCoSp2', 'Flying Combination Spin no change of foot with 2 spin', 2),
       ('FCoSp2V', 'Flying Combination Spin no change of foot with 2 spin V', 1.5),
       ('FCoSp3', 'Flying Combination Spin no change of foot with 3 spin', 2.5),
       ('FCoSp3V', 'Flying Combination Spin no change of foot with 3 spin V', 1.88),
       ('FCoSp4', 'Flying Combination Spin no change of foot with 4 spin', 3),
       ('FCoSp4V', 'Flying Combination Spin no change of foot with 4 spin V', 2.25),
       ('FCoSpB', 'Flying Combination Spin no change of foot with B spin', 1.5),
       ('FCoSpBV', 'Flying Combination Spin no change of foot with B spin V', 1.13),
       ('FLSp1', 'Flying Layback Spin with 1 spin', 2),
       ('FLSp1V', 'Flying Layback Spin with 1 spin V', 1.5),
       ('FLSp2', 'Flying Layback Spin with 2 spin', 2.4),
       ('FLSp2V', 'Flying Layback Spin with 2 spin V', 1.8),
       ('FLSp3', 'Flying Layback Spin with 3 spin', 2.9),
       ('FLSp3V', 'Flying Layback Spin with 3 spin V', 2.18),
       ('FLSp4', 'Flying Layback Spin with 4 spin', 3.2),
       ('FLSp4V', 'Flying Layback Spin with 4 spin V', 2.4),
       ('FLSpB', 'Flying Layback Spin with B spin', 1.7),
       ('FLSpBV', 'Flying Layback Spin with B spin V', 1.28),
       ('FSSp1', 'Flying Sit Spin with 1 spin', 2),
       ('FSSp1V', 'Flying Sit Spin with 1 spin V', 1.5),
       ('FSSp2', 'Flying Sit Spin with 2 spin', 2.3),
       ('FSSp2V', 'Flying Sit Spin with 2 spin V', 1.73),
       ('FSSp3', 'Flying Sit Spin with 3 spin', 2.6),
       ('FSSp3V', 'Flying Sit Spin with 3 spin V', 1.95),
       ('FSSp4', 'Flying Sit Spin with 4 spin', 3),
       ('FSSp4V', 'Flying Sit Spin with 4 spin V', 2.25),
       ('FSSpB', 'Flying Sit Spin with B spin', 1.7),
       ('FSSpBV', 'Flying Sit Spin with B spin V', 1.28),
       ('FUSp1', 'Flying Upright Spin with 1 spin', 1.7),
       ('FUSp1V', 'Flying Upright Spin with 1 spin V', 1.28),
       ('FUSp2', 'Flying Upright Spin with 2 spin', 2),
       ('FUSp2V', 'Flying Upright Spin with 2 spin V', 1.5),
       ('FUSp3', 'Flying Upright Spin with 3 spin', 2.4),
       ('FUSp3V', 'Flying Upright Spin with 3 spin V', 1.8),
       ('FUSp4', 'Flying Upright Spin with 4 spin', 2.9),
       ('FUSp4V', 'Flying Upright Spin with 4 spin V', 2.18),
       ('FUSpB', 'Flying Upright Spin with B spin', 1.5),
       ('FUSpBV', 'Flying Upright Spin with B spin V', 1.13),
       ('LSp1', 'Layback Spin with 1 spin', 1.5),
       ('LSp2', 'Layback Spin with 2 spin', 1.9),
       ('LSp3', 'Layback Spin with 3 spin', 2.4),
       ('LSp4', 'Layback Spin with 4 spin', 2.7),
       ('LSpB', 'Layback Spin with B spin', 1.2),
       ('PCoSp1', 'Pair Combination Spin with 1 spin', 3),
       ('PCoSp1V', 'Pair Combination Spin with 1 spin V', 2.25),
       ('PCoSp2', 'Pair Combination Spin with 2 spin', 3.5),
       ('PCoSp2V', 'Pair Combination Spin with 2 spin V', 2.63),
       ('PCoSp3', 'Pair Combination Spin with 3 spin', 4),
       ('PCoSp3V', 'Pair Combination Spin with 3 spin V', 3),
       ('PCoSp4', 'Pair Combination Spin with 4 spin', 4.5),
       ('PCoSp4V', 'Pair Combination Spin with 4 spin V', 3.38),
       ('PCoSpB', 'Pair Combination Spin with B spin', 2.5),
       ('PCoSpBV', 'Pair Combination Spin with B spin V', 1.88),
       ('PSp1', 'Pair Spin with 1 spin', 2),
       ('PSp2', 'Pair Spin with 2 spin', 2.5),
       ('PSp3', 'Pair Spin with 3 spin', 3),
       ('PSp4', 'Pair Spin with 4 spin', 3.5),
       ('PSpB', 'Pair Spin with B spin', 1.7),
       ('PiF', 'Pivot Figure', 2.2),
       ('SSp1', 'Sit Spin with 1 spin', 1.3),
       ('SSp2', 'Sit Spin with 2 spin', 1.6),
       ('SSp3', 'Sit Spin with 3 spin', 2.1),
       ('SSp4', 'Sit Spin with 4 spin', 2.5),
       ('SSpB', 'Sit Spin with B spin', 1.1),
       ('StSq1', 'Step Sequence with 1 spin', 1.8),
       ('StSq2', 'Step Sequence with 2 spin', 2.6),
       ('StSq3', 'Step Sequence with 3 spin', 3.3),
       ('StSq4', 'Step Sequence with 4 spin', 3.9),
       ('StSqB', 'Step Sequence with B spin', 1.5),
       ('USp1', 'Upright Spin with 1 spin', 1.2),
       ('USp2', 'Upright Spin with 2 spin', 1.5),
       ('USp3', 'Upright Spin with 3 spin', 1.9),
       ('USp4', 'Upright Spin with 4 spin', 2.4),
       ('USpB', 'Upright Spin with B spin', 1);
